// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { GetStateRequest, GetStateRequestT } from '../debugger/get-state-request.js';
import { GetStateResponse, GetStateResponseT } from '../debugger/get-state-response.js';
import { PauseRequest, PauseRequestT } from '../debugger/pause-request.js';
import { RunRequest, RunRequestT } from '../debugger/run-request.js';


export enum Event {
  NONE = 0,
  PauseRequest = 1,
  RunRequest = 2,
  GetStateRequest = 3,
  GetStateResponse = 4
}

export function unionToEvent(
  type: Event,
  accessor: (obj:GetStateRequest|GetStateResponse|PauseRequest|RunRequest) => GetStateRequest|GetStateResponse|PauseRequest|RunRequest|null
): GetStateRequest|GetStateResponse|PauseRequest|RunRequest|null {
  switch(Event[type]) {
    case 'NONE': return null; 
    case 'PauseRequest': return accessor(new PauseRequest())! as PauseRequest;
    case 'RunRequest': return accessor(new RunRequest())! as RunRequest;
    case 'GetStateRequest': return accessor(new GetStateRequest())! as GetStateRequest;
    case 'GetStateResponse': return accessor(new GetStateResponse())! as GetStateResponse;
    default: return null;
  }
}

export function unionListToEvent(
  type: Event, 
  accessor: (index: number, obj:GetStateRequest|GetStateResponse|PauseRequest|RunRequest) => GetStateRequest|GetStateResponse|PauseRequest|RunRequest|null, 
  index: number
): GetStateRequest|GetStateResponse|PauseRequest|RunRequest|null {
  switch(Event[type]) {
    case 'NONE': return null; 
    case 'PauseRequest': return accessor(index, new PauseRequest())! as PauseRequest;
    case 'RunRequest': return accessor(index, new RunRequest())! as RunRequest;
    case 'GetStateRequest': return accessor(index, new GetStateRequest())! as GetStateRequest;
    case 'GetStateResponse': return accessor(index, new GetStateResponse())! as GetStateResponse;
    default: return null;
  }
}
