// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class GetStateRequest implements flatbuffers.IUnpackableObject<GetStateRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetStateRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetStateRequest(bb:flatbuffers.ByteBuffer, obj?:GetStateRequest):GetStateRequest {
  return (obj || new GetStateRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetStateRequest(bb:flatbuffers.ByteBuffer, obj?:GetStateRequest):GetStateRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetStateRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startGetStateRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endGetStateRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetStateRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  GetStateRequest.startGetStateRequest(builder);
  return GetStateRequest.endGetStateRequest(builder);
}

unpack(): GetStateRequestT {
  return new GetStateRequestT();
}


unpackTo(_o: GetStateRequestT): void {}
}

export class GetStateRequestT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return GetStateRequest.createGetStateRequest(builder);
}
}
