// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class PauseRequest implements flatbuffers.IUnpackableObject<PauseRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PauseRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPauseRequest(bb:flatbuffers.ByteBuffer, obj?:PauseRequest):PauseRequest {
  return (obj || new PauseRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPauseRequest(bb:flatbuffers.ByteBuffer, obj?:PauseRequest):PauseRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PauseRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startPauseRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endPauseRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPauseRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  PauseRequest.startPauseRequest(builder);
  return PauseRequest.endPauseRequest(builder);
}

unpack(): PauseRequestT {
  return new PauseRequestT();
}


unpackTo(_o: PauseRequestT): void {}
}

export class PauseRequestT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return PauseRequest.createPauseRequest(builder);
}
}
